kind: Service
apiVersion: v1
metadata:
  name: docker-kubernetes
spec:
  selector:
    app: docker-kubernetes
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-kubernetes
spec:
  selector:
      matchLabels:
        app: docker-kubernetes
        tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-kubernetes
        tier: backend
    spec:
      containers:
        - name: docker-kubernetes
          image: docker-kubernetes:5f8f537
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

